### ISSUE TITLE
Sorry for advertising but I have a better tool for this

### ISSUE THREAD

**Issue by Iapetus-11** [SeasideDevs/Lighthouse#4]
Your brain, learn how to count.

**Comment by TheLimifiedLime** [comment]
Kinda time consuming to do when your in a bunch of servers you know?

**Comment by Iapetus-11** [comment]
Not as time consuming as searching for a website to count them

**Comment by TheLimifiedLime** [comment]
Then don't look for one? You wouldn't even find this place by searching as Google doesn't even show it when you put the whole URL in.

**Comment by Iapetus-11** [comment]
yes
